### PR TITLE
docker: installation instruction fix

### LINKED ISSUE #67: installation: better docker startup
Starting an instance the first time, one now gets:

```console
$ docker-compose build
[...]
$ docker-compose up
[...]
web_1 |   File "/usr/local/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
web_1 |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
web_1 | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
web_1 |         Is the server running on host "db" (172.17.0.26) and accepting
web_1 |         TCP/IP connections on port 5432?
web_1 | 
claimstore_web_1 exited with code 1
```

An immediate restart works though: 

```console
$ docker-compose up
Recreating claimstore_db_1...
Recreating claimstore_web_1...
Attaching to claimstore_db_1, claimstore_web_1
db_1  | LOG:  database system was interrupted; last known up at 2015-09-18 16:13:27 UTC
db_1  | LOG:  database system was not properly shut down; automatic recovery in progress
db_1  | LOG:  record with zero length at 0/16A8178
db_1  | LOG:  redo is not required
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
web_1 | Database initialisation completed.
web_1 | Database populate completed.
web_1 |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
web_1 |  * Restarting with stat
```

Would be good to get the first-time startup right.

### PR DESCRIPTION
**Pull request by tiborsimko**
* Fixes (and simplifies) Docker installation instructions. (closes #67)

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by jbenito3** [comment]
@tiborsimko could you please also add the new instructions in `docs/installation.rst`?

**Comment by jbenito3** [comment]
@tiborsimko as well:

```
$ docker-compose run --rm web claimstore /code/run-tests.sh
Traceback (most recent call last):
  ...
AttributeError: 'Flask' object has no attribute 'cli'
```

The tests work fine locally.

**Comment by tiborsimko** [comment]
> could you please also add the new instructions in docs/installation.rst?

Done and re-pushed.

> AttributeError: 'Flask' object has no attribute 'cli'

Hmm, I cannot reproduce this.  (Although I saw this at one stage...)  

Here is how I try from a clean slate:

```
cd ~/private/src/claimstore
rm -rf claimstore/static/vendors/
docker ps -a | grep claimstore | awk '{print $1;}' | xargs docker rm -f
docker images | grep claimstore | awk '{print $3;}' | xargs docker rmi -f
docker-compose build --no-cache
docker-compose run --rm web bower install
docker-compose run --rm web claimstore database create
docker-compose run --rm web claimstore database populate
docker-compose run --rm web /code/run-tests.sh
docker-compose up
```

and all is well.

**Comment by jbenito3** [comment]
@tiborsimko merged. For some reason it was working for me as well today...weird...

**Pull request merged**
